IMAGE_QUESTIONS = {
    "capitals": [
        {"q": "لأي دولة هذا العلم؟", "opts": ["الدنمارك", "الكويت", "السعودية", "الجزائر"], "a": 2, "img": "https://flagcdn.com/w320/sa.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["تونس", "جنوب أفريقيا", "الإمارات", "فلسطين"], "a": 2, "img": "https://flagcdn.com/w320/ae.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["فلسطين", "بلجيكا", "أيرلندا", "مصر"], "a": 3, "img": "https://flagcdn.com/w320/eg.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["قطر", "جنوب أفريقيا", "سنغافورة", "هولندا"], "a": 0, "img": "https://flagcdn.com/w320/qa.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["إيران", "الكويت", "السعودية", "جزر القمر"], "a": 1, "img": "https://flagcdn.com/w320/kw.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["اليابان", "تونس", "أيرلندا", "البحرين"], "a": 3, "img": "https://flagcdn.com/w320/bh.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["النرويج", "الهند", "كوريا الجنوبية", "عمان"], "a": 3, "img": "https://flagcdn.com/w320/om.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["إندونيسيا", "نيوزيلندا", "ليبيا", "الأردن"], "a": 3, "img": "https://flagcdn.com/w320/jo.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["باكستان", "غانا", "إسبانيا", "لبنان"], "a": 3, "img": "https://flagcdn.com/w320/lb.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["بلجيكا", "اليمن", "اليونان", "سوريا"], "a": 3, "img": "https://flagcdn.com/w320/sy.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["جزر القمر", "العراق", "كندا", "باكستان"], "a": 1, "img": "https://flagcdn.com/w320/iq.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["سوريا", "فرنسا", "اليمن", "فنلندا"], "a": 2, "img": "https://flagcdn.com/w320/ye.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["فلسطين", "كينيا", "فنلندا", "إندونيسيا"], "a": 0, "img": "https://flagcdn.com/w320/ps.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["المغرب", "الكويت", "الأردن", "بلجيكا"], "a": 0, "img": "https://flagcdn.com/w320/ma.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["إثيوبيا", "لبنان", "تونس", "أيرلندا"], "a": 2, "img": "https://flagcdn.com/w320/tn.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["فيتنام", "موريتانيا", "الجزائر", "كندا"], "a": 2, "img": "https://flagcdn.com/w320/dz.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["ليبيا", "كينيا", "نيوزيلندا", "النرويج"], "a": 0, "img": "https://flagcdn.com/w320/ly.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["باكستان", "هولندا", "السودان", "الصومال"], "a": 2, "img": "https://flagcdn.com/w320/sd.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["تونس", "الصومال", "جيبوتي", "جزر القمر"], "a": 1, "img": "https://flagcdn.com/w320/so.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["موريتانيا", "تايلاند", "إندونيسيا", "تنزانيا"], "a": 0, "img": "https://flagcdn.com/w320/mr.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["جيبوتي", "نيجيريا", "تونس", "الإمارات"], "a": 0, "img": "https://flagcdn.com/w320/dj.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["اليونان", "جزر القمر", "أفغانستان", "تونس"], "a": 1, "img": "https://flagcdn.com/w320/km.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["ألمانيا", "النرويج", "بيرو", "فرنسا"], "a": 3, "img": "https://flagcdn.com/w320/fr.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["بيرو", "موريتانيا", "ألمانيا", "البرتغال"], "a": 2, "img": "https://flagcdn.com/w320/de.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["تركيا", "تنزانيا", "تشيلي", "إيطاليا"], "a": 3, "img": "https://flagcdn.com/w320/it.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["الأردن", "إسبانيا", "سويسرا", "أوكرانيا"], "a": 1, "img": "https://flagcdn.com/w320/es.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["تشيلي", "لبنان", "البرتغال", "العراق"], "a": 2, "img": "https://flagcdn.com/w320/pt.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["نيجيريا", "جزر القمر", "بريطانيا", "النرويج"], "a": 2, "img": "https://flagcdn.com/w320/gb.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["أيرلندا", "أوكرانيا", "الفلبين", "بنغلاديش"], "a": 0, "img": "https://flagcdn.com/w320/ie.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["النمسا", "أيرلندا", "الجزائر", "هولندا"], "a": 3, "img": "https://flagcdn.com/w320/nl.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["هولندا", "نيجيريا", "بلجيكا", "السنغال"], "a": 2, "img": "https://flagcdn.com/w320/be.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["هولندا", "لبنان", "الأردن", "سويسرا"], "a": 3, "img": "https://flagcdn.com/w320/ch.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["فنزويلا", "بلجيكا", "النمسا", "الدنمارك"], "a": 2, "img": "https://flagcdn.com/w320/at.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["البرازيل", "السويد", "غانا", "سويسرا"], "a": 1, "img": "https://flagcdn.com/w320/se.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["النرويج", "أفغانستان", "فلسطين", "الهند"], "a": 0, "img": "https://flagcdn.com/w320/no.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["فنلندا", "عمان", "فلسطين", "الأردن"], "a": 0, "img": "https://flagcdn.com/w320/fi.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["الدنمارك", "إيطاليا", "سويسرا", "المغرب"], "a": 0, "img": "https://flagcdn.com/w320/dk.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["ألمانيا", "بولندا", "السودان", "إيران"], "a": 1, "img": "https://flagcdn.com/w320/pl.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["سوريا", "كازاخستان", "نيجيريا", "اليونان"], "a": 3, "img": "https://flagcdn.com/w320/gr.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["روسيا", "بلجيكا", "اليمن", "جزر القمر"], "a": 0, "img": "https://flagcdn.com/w320/ru.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["الفلبين", "أوكرانيا", "الأردن", "بريطانيا"], "a": 1, "img": "https://flagcdn.com/w320/ua.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["رومانيا", "كندا", "تايلاند", "السويد"], "a": 0, "img": "https://flagcdn.com/w320/ro.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["بولندا", "إيطاليا", "تركيا", "موريتانيا"], "a": 2, "img": "https://flagcdn.com/w320/tr.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["أوكرانيا", "الصين", "الأردن", "عمان"], "a": 1, "img": "https://flagcdn.com/w320/cn.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["العراق", "فنزويلا", "اليابان", "الأردن"], "a": 2, "img": "https://flagcdn.com/w320/jp.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["الجزائر", "كوريا الجنوبية", "الفلبين", "بلجيكا"], "a": 1, "img": "https://flagcdn.com/w320/kr.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["ساحل العاج", "الهند", "العراق", "سنغافورة"], "a": 1, "img": "https://flagcdn.com/w320/in.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["بلجيكا", "أوكرانيا", "باكستان", "السويد"], "a": 2, "img": "https://flagcdn.com/w320/pk.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["أوكرانيا", "سوريا", "كندا", "بنغلاديش"], "a": 3, "img": "https://flagcdn.com/w320/bd.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["بريطانيا", "سوريا", "إندونيسيا", "نيوزيلندا"], "a": 2, "img": "https://flagcdn.com/w320/id.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["باكستان", "لبنان", "تايلاند", "سويسرا"], "a": 2, "img": "https://flagcdn.com/w320/th.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["أستراليا", "جنوب أفريقيا", "اليونان", "فيتنام"], "a": 3, "img": "https://flagcdn.com/w320/vn.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["المغرب", "السودان", "السويد", "الفلبين"], "a": 3, "img": "https://flagcdn.com/w320/ph.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["البرتغال", "النرويج", "ماليزيا", "الدنمارك"], "a": 2, "img": "https://flagcdn.com/w320/my.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["تشيلي", "بيرو", "النمسا", "سنغافورة"], "a": 3, "img": "https://flagcdn.com/w320/sg.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["السعودية", "فنلندا", "إيران", "البحرين"], "a": 2, "img": "https://flagcdn.com/w320/ir.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["جيبوتي", "أفغانستان", "كازاخستان", "نيجيريا"], "a": 1, "img": "https://flagcdn.com/w320/af.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["سوريا", "موريتانيا", "تونس", "كازاخستان"], "a": 3, "img": "https://flagcdn.com/w320/kz.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["البحرين", "أمريكا", "إيران", "ليبيا"], "a": 1, "img": "https://flagcdn.com/w320/us.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["سويسرا", "البرتغال", "كوريا الجنوبية", "كندا"], "a": 3, "img": "https://flagcdn.com/w320/ca.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["بلجيكا", "المكسيك", "جيبوتي", "موريتانيا"], "a": 1, "img": "https://flagcdn.com/w320/mx.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["تركيا", "البرازيل", "الفلبين", "فرنسا"], "a": 1, "img": "https://flagcdn.com/w320/br.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["المغرب", "بنغلاديش", "الأرجنتين", "الكويت"], "a": 2, "img": "https://flagcdn.com/w320/ar.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["روسيا", "اليابان", "تشيلي", "أمريكا"], "a": 2, "img": "https://flagcdn.com/w320/cl.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["تركيا", "إيطاليا", "كولومبيا", "فيتنام"], "a": 2, "img": "https://flagcdn.com/w320/co.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["اليابان", "فيتنام", "بيرو", "فنزويلا"], "a": 2, "img": "https://flagcdn.com/w320/pe.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["السويد", "ساحل العاج", "فنزويلا", "فرنسا"], "a": 2, "img": "https://flagcdn.com/w320/ve.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["اليابان", "كوبا", "تنزانيا", "إيران"], "a": 1, "img": "https://flagcdn.com/w320/cu.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["إيطاليا", "إندونيسيا", "أستراليا", "غانا"], "a": 2, "img": "https://flagcdn.com/w320/au.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["نيوزيلندا", "فنزويلا", "أستراليا", "السعودية"], "a": 0, "img": "https://flagcdn.com/w320/nz.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["أوكرانيا", "لبنان", "تركيا", "جنوب أفريقيا"], "a": 3, "img": "https://flagcdn.com/w320/za.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["نيجيريا", "الفلبين", "كولومبيا", "روسيا"], "a": 0, "img": "https://flagcdn.com/w320/ng.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["كينيا", "جنوب أفريقيا", "ليبيا", "إيطاليا"], "a": 0, "img": "https://flagcdn.com/w320/ke.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["فرنسا", "إثيوبيا", "كينيا", "اليونان"], "a": 1, "img": "https://flagcdn.com/w320/et.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["غانا", "اليونان", "الدنمارك", "البرتغال"], "a": 0, "img": "https://flagcdn.com/w320/gh.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["كندا", "ساحل العاج", "أفغانستان", "بريطانيا"], "a": 1, "img": "https://flagcdn.com/w320/ci.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["العراق", "بيرو", "السنغال", "الدنمارك"], "a": 2, "img": "https://flagcdn.com/w320/sn.png"},
        {"q": "لأي دولة هذا العلم؟", "opts": ["إسبانيا", "أيرلندا", "تنزانيا", "روسيا"], "a": 2, "img": "https://flagcdn.com/w320/tz.png"},
        {"q": "أي هذه الأعلام هو علم سويسرا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/ch.png", "https://flagcdn.com/w160/ke.png", "https://flagcdn.com/w160/tz.png", "https://flagcdn.com/w160/ro.png"], "a": 0},
        {"q": "أي هذه الأعلام هو علم المكسيك؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/mx.png", "https://flagcdn.com/w160/kz.png", "https://flagcdn.com/w160/ng.png", "https://flagcdn.com/w160/dj.png"], "a": 0},
        {"q": "أي هذه الأعلام هو علم سوريا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/at.png", "https://flagcdn.com/w160/sy.png", "https://flagcdn.com/w160/dk.png", "https://flagcdn.com/w160/cu.png"], "a": 1},
        {"q": "أي هذه الأعلام هو علم أمريكا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/sy.png", "https://flagcdn.com/w160/fi.png", "https://flagcdn.com/w160/us.png", "https://flagcdn.com/w160/af.png"], "a": 2},
        {"q": "أي هذه الأعلام هو علم ماليزيا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/tr.png", "https://flagcdn.com/w160/ua.png", "https://flagcdn.com/w160/za.png", "https://flagcdn.com/w160/my.png"], "a": 3},
        {"q": "أي هذه الأعلام هو علم إيطاليا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/th.png", "https://flagcdn.com/w160/mr.png", "https://flagcdn.com/w160/it.png", "https://flagcdn.com/w160/be.png"], "a": 2},
        {"q": "أي هذه الأعلام هو علم إندونيسيا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/tr.png", "https://flagcdn.com/w160/id.png", "https://flagcdn.com/w160/my.png", "https://flagcdn.com/w160/za.png"], "a": 1},
        {"q": "أي هذه الأعلام هو علم تشيلي؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/id.png", "https://flagcdn.com/w160/pt.png", "https://flagcdn.com/w160/my.png", "https://flagcdn.com/w160/cl.png"], "a": 3},
        {"q": "أي هذه الأعلام هو علم فيتنام؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/vn.png", "https://flagcdn.com/w160/kr.png", "https://flagcdn.com/w160/ar.png", "https://flagcdn.com/w160/sa.png"], "a": 0},
        {"q": "أي هذه الأعلام هو علم تنزانيا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/nz.png", "https://flagcdn.com/w160/au.png", "https://flagcdn.com/w160/tz.png", "https://flagcdn.com/w160/ie.png"], "a": 2},
        {"q": "أي هذه الأعلام هو علم الصومال؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/so.png", "https://flagcdn.com/w160/cl.png", "https://flagcdn.com/w160/af.png", "https://flagcdn.com/w160/qa.png"], "a": 0},
        {"q": "أي هذه الأعلام هو علم السعودية؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/mx.png", "https://flagcdn.com/w160/sd.png", "https://flagcdn.com/w160/fr.png", "https://flagcdn.com/w160/sa.png"], "a": 3},
        {"q": "أي هذه الأعلام هو علم المغرب؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/iq.png", "https://flagcdn.com/w160/ir.png", "https://flagcdn.com/w160/ma.png", "https://flagcdn.com/w160/so.png"], "a": 2},
        {"q": "أي هذه الأعلام هو علم سنغافورة؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/sg.png", "https://flagcdn.com/w160/bd.png", "https://flagcdn.com/w160/ro.png", "https://flagcdn.com/w160/se.png"], "a": 0},
        {"q": "أي هذه الأعلام هو علم أيرلندا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/id.png", "https://flagcdn.com/w160/ie.png", "https://flagcdn.com/w160/jp.png", "https://flagcdn.com/w160/dk.png"], "a": 1},
        {"q": "أي هذه الأعلام هو علم اليمن؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/eg.png", "https://flagcdn.com/w160/za.png", "https://flagcdn.com/w160/br.png", "https://flagcdn.com/w160/ye.png"], "a": 3},
        {"q": "أي هذه الأعلام هو علم نيوزيلندا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/qa.png", "https://flagcdn.com/w160/bh.png", "https://flagcdn.com/w160/nz.png", "https://flagcdn.com/w160/lb.png"], "a": 2},
        {"q": "أي هذه الأعلام هو علم اليابان؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/mr.png", "https://flagcdn.com/w160/jp.png", "https://flagcdn.com/w160/be.png", "https://flagcdn.com/w160/ly.png"], "a": 1},
        {"q": "أي هذه الأعلام هو علم السويد؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/mx.png", "https://flagcdn.com/w160/se.png", "https://flagcdn.com/w160/et.png", "https://flagcdn.com/w160/gb.png"], "a": 1},
        {"q": "أي هذه الأعلام هو علم هولندا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/tn.png", "https://flagcdn.com/w160/ua.png", "https://flagcdn.com/w160/dj.png", "https://flagcdn.com/w160/nl.png"], "a": 3},
        {"q": "أي هذه الأعلام هو علم قطر؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/ua.png", "https://flagcdn.com/w160/qa.png", "https://flagcdn.com/w160/gh.png", "https://flagcdn.com/w160/id.png"], "a": 1},
        {"q": "أي هذه الأعلام هو علم فنلندا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/ch.png", "https://flagcdn.com/w160/sy.png", "https://flagcdn.com/w160/sn.png", "https://flagcdn.com/w160/fi.png"], "a": 3},
        {"q": "أي هذه الأعلام هو علم الجزائر؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/et.png", "https://flagcdn.com/w160/ly.png", "https://flagcdn.com/w160/tz.png", "https://flagcdn.com/w160/dz.png"], "a": 3},
        {"q": "أي هذه الأعلام هو علم كولومبيا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/pe.png", "https://flagcdn.com/w160/pk.png", "https://flagcdn.com/w160/co.png", "https://flagcdn.com/w160/lb.png"], "a": 2},
        {"q": "أي هذه الأعلام هو علم الأردن؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/jo.png", "https://flagcdn.com/w160/cl.png", "https://flagcdn.com/w160/af.png", "https://flagcdn.com/w160/tn.png"], "a": 0},
        {"q": "أي هذه الأعلام هو علم غانا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/gh.png", "https://flagcdn.com/w160/mr.png", "https://flagcdn.com/w160/fr.png", "https://flagcdn.com/w160/ir.png"], "a": 0},
        {"q": "أي هذه الأعلام هو علم لبنان؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/sn.png", "https://flagcdn.com/w160/lb.png", "https://flagcdn.com/w160/mx.png", "https://flagcdn.com/w160/af.png"], "a": 1},
        {"q": "أي هذه الأعلام هو علم الفلبين؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/ph.png", "https://flagcdn.com/w160/fi.png", "https://flagcdn.com/w160/us.png", "https://flagcdn.com/w160/ye.png"], "a": 0},
        {"q": "أي هذه الأعلام هو علم تركيا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/co.png", "https://flagcdn.com/w160/jp.png", "https://flagcdn.com/w160/tr.png", "https://flagcdn.com/w160/qa.png"], "a": 2},
        {"q": "أي هذه الأعلام هو علم كندا؟", "opts": ["أ", "ب", "ج", "د"], "opts_img": ["https://flagcdn.com/w160/ca.png", "https://flagcdn.com/w160/se.png", "https://flagcdn.com/w160/gb.png", "https://flagcdn.com/w160/kr.png"], "a": 0},
    ],
}

QUOTE_QUESTIONS = {
    "literature": [
        {"q": "أكمل: 'الخيل والليل والبيداء تعرفني ...'", "opts": ["والسيف والرمح والقرطاس والقلم", "والدرع والخنجر والسهم والوتر", "والقلب والحرف والقافية والألم", "والعز والمجد والإقدام والهمم"], "a": 0},
        {"q": "أكمل قصيدة: 'إذا الشعب يوماً أراد الحياة ...'", "opts": ["فلا بد أن يستجيب القدر", "فلا يقعدنّ به الكسل", "فمن يقو دون سلاح يفز", "فقد كتب النصر لمن صبر"], "a": 0},
        {"q": "من قال: 'أنا الغريق فما خوفي من البلل'؟", "opts": ["المتنبي", "أبو العلاء المعري", "أحمد شوقي", "نزار قباني"], "a": 1},
        {"q": "أكمل: 'وما نيل المطالب بالتمني ...'", "opts": ["ولكن تؤخذ الدنيا غلابا", "ولكنّ الأماني ضلال", "ولكن بجدّ في الطلاب", "ولكنه بالحلم يستدرك"], "a": 0},
    ],
    "quran": [
        {"q": "أكمل: 'وما خلقت الجن والإنس ...'", "opts": ["إلا ليعبدون", "إلا ليعمروا", "إلا ليعرفون", "إلا ليشكرون"], "a": 0},
        {"q": "أكمل: 'إن مع العسر ...'", "opts": ["فرجاً", "يسراً", "راحة", "مخرجاً"], "a": 1},
        {"q": "أكمل: 'ولا تقنطوا من رحمة الله ...'", "opts": ["إن الله غفور رحيم", "إن الله يغفر الذنوب جميعاً", "إن الله على كل شيء قدير", "إن رحمة الله قريب من المحسنين"], "a": 1},
        {"q": "أكمل: 'واعتصموا بحبل الله جميعاً ...'", "opts": ["ولا تفرقوا", "وكونوا عباد الله إخوانا", "واذكروا نعمة الله عليكم", "ولا تنازعوا"], "a": 0},
    ],
    "celebs": [
        {"q": "من قال: 'أعطني قلماً أعطيك شعباً واعياً'؟", "opts": ["جمال عبد الناصر", "طه حسين", "أحمد لطفي السيد", "أحمد شوقي"], "a": 3},
        {"q": "من قال: 'أنا أفكر إذاً أنا موجود'؟", "opts": ["أفلاطون", "أرسطو", "ديكارت", "سقراط"], "a": 2},
    ],
}
